---
- hosts: nat
  roles:
  - nat
- hosts: protected
  roles:
  - protected
- hosts: orchestrators
  roles:
  - orchestrator
  - tools
  - operators
- hosts: nodes
  roles:
  - node
  - tools
- hosts: orchestrators
  roles:
  - orchestrator_finalized
