- name: Ensure system is up to date
  yum:
    name: "*"
    state: latest

- name: Ensure important and useful packages are installed
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - unzip
      - chrony
      - python3-libselinux
      - man
      - tmux
      - vim-enhanced
      - wget
      - java-11-openjdk-devel
      - gnupg
